title: Phylogenetic reconstruction
description: >- # this means to ignore newlines until "baseurl:"
  R lab. 
baseurl: "/BioSci700" # the subpath of your site, e.g. /blog
url: "http://walterxie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  walterxie


# Build settings
markdown: kramdown
mathjax: true

# Build settings
theme: minima
header_pages:
  - files.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag