title: BioSci700 Labs
description: >- # this means to ignore newlines until "baseurl:"
  BioSci700 labs. 
baseurl: "/BioSci700" # the subpath of your site, e.g. /blog
url: "http://walterxie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  walterxie


# Build settings
markdown: kramdown
mathjax: true

# Build settings
theme: minima
header_pages:
  - index.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

# https://github.com/mmistakes/minimal-mistakes/issues/1618
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true


