---
title: "Simple R examples"
output: html_document
date: "2024-03-13"
---


## Paste string

```{r}
# has a space between A and B
paste("A", "B")
# no spaces
paste0("A", "B")

str = "C"
# append A to the beginning
str = paste0("A", str)
str
# append B to the end
str = paste0(str, "B")
str
```

## If else

```{r}
x = "A"
if (x == "A") {
  print(x)
} else if (x == "B") {
  print(x)
} else {
  stop("Err : x must be either A or B !")
}
```

Inline ifelse

```{r}
match = 1
mismatch = -1
# if TRUE then match
s = ifelse(TRUE, match, mismatch)
print(s)
# else mismatch
s = ifelse(FALSE, match, mismatch)
print(s)
```


## Get matrix value by row/col name

```{r}
S = matrix(c(2, 1, -2, 0), nrow = 2)
rownames(S) <- c("A","B")
colnames(S) <- c("C","D")
print(S)
```
```{r}
# by index
print(S[1,2])
# by name
print(S["A","D"])

# assign value
S[1,2] = 3
print(S[1,2])
```
## For loop

```{r}
for (i in 1:3) {
  cat("i = ", i ,"\n")
}
```

```{r}
for (i in 1:3) {
  for (j in 1:3) {
    cat("i = ", i ,", j = ", j ,"\n")
  }
}
```

## Math

```{r}
max(1,2)
max(1,2,3)
```


```{r}
F = matrix(c(1,1,2,1, 1,1,1,2, 1,2,1,1), nrow = 3)
F
max_score = max(F)
# max_i, max_j are the coordinate of the highest score max_score in F matrix. 
co = which(F==max_score, arr.ind=TRUE)
co
max_i = co[nrow(co),1]  
max_j = co[nrow(co),2]
#[2,3] is rightmost position 
paste(max_i, max_j)
```
```{r}
F = matrix(c(1,1,2,1, 1,1,1,2, 1,2,1,2), nrow = 3)
F
max_score = max(F)
# max_i, max_j are the coordinate of the highest score max_score in F matrix. 
co = which(F==max_score, arr.ind=TRUE)
co
max_i = co[nrow(co),1]  
max_j = co[nrow(co),2]
#[2,3] is rightmost position 
paste(max_i, max_j)
```
